---
- name: Install John the Ripper on Ubuntu servers
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache is considered valid for 1 hour

    - name: Install John the Ripper
      ansible.builtin.apt:
        name: john
        state: present
