---
- name: install_nmap
  hosts: all
  become: yes       # This enables privilege escalation
  become_method: sudo  # This specifies to use sudo for becoming another user
  tasks:
    - name: Task 1
      apt:
        name: nmap
        state: present
        update_cache: yes
        force_apt_get: yes
        autoclean: yes
        autoremove: yes
