---
- name: Update and upgrade all Ubuntu servers to the latest version
  hosts: ubuntu_servers
  become: yes

  tasks:
    - name: Ensure the apt cache is updated
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Clean up apt cache
      ansible.builtin.apt:
        autoclean: yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required
      ignore_errors: true

    - name: Reboot the server if required
      ansible.builtin.reboot:
        msg: "Rebooting because of a system upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Wait for the server to come back
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300
      when: reboot_required_file.stat.exists
