---
- name: Update all Ubuntu servers to the latest version
  hosts: all
  become: yes

  tasks:
    - name: Ensure the apt cache is updated
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes

    - name: Clean up apt cache
      ansible.builtin.apt:
        autoclean: yes
