---
- name: Update and upgrade all packages on all hosts
  hosts: all
  tasks:
    - name: Update package lists
      ansible.builtin.apt:
        update_cache: yes
      become: no

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      become: no
