---
- name: Update & Upgrade
  hosts: all
  tasks:
    - name: Task 1
      apt:
        name: update
        state: present
        update_cache: yes
        force_apt_get: yes
        autoclean: yes
        autoremove: yes
  
