---
- name: Update package if installed
  hosts: all
  become: yes  # if you need root privileges
  tasks:
    - name: Check if 'ncdu' is installed
      ansible.builtin.command: dpkg -l ncdu
      register: dpkg_result
      failed_when: dpkg_result.rc != 0 and dpkg_result.rc != 1
      changed_when: false
      check_mode: false

    - name: Update 'ncdu' if it is installed
      ansible.builtin.apt:
        name: ncdu
        state: latest
      when: dpkg_result.rc == 0
